### ISSUE TITLE
Error start Plugin 

### ISSUE THREAD

**Issue by alexfernandojs** [ioridev/flutter_applovin_max#10]
Not Start !! LOG

c:\src\.pub-cache\hosted\pub.dartlang.org\flutter_applovin_max-0.0.3\android\src\main\java\dev\iori\flutter_applovin_max\RewardedVideo.java:20: error: RewardedVideo is not abstract and does not override abstract method onAdDisplayFailed(MaxAd,MaxError) in MaxAdListener
public class RewardedVideo implements MaxRewardedAdListener {
       ^
c:\src\.pub-cache\hosted\pub.dartlang.org\flutter_applovin_max-0.0.3\android\src\main\java\dev\iori\flutter_applovin_max\RewardedVideo.java:49: error: method does not override or implement a method from a supertype
    @Override
    ^
c:\src\.pub-cache\hosted\pub.dartlang.org\flutter_applovin_max-0.0.3\android\src\main\java\dev\iori\flutter_applovin_max\RewardedVideo.java:72: error: method does not override or implement a method from a supertype

    @Override
    ^
Note: c:\src\.pub-cache\hosted\pub.dartlang.org\flutter_applovin_max-0.0.3\android\src\main\java\dev\iori\flutter_applovin_max\FlutterApplovinMaxPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_applovin_max:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by superkeka** [comment]
#11 Fixed in this PR
