### ISSUE TITLE
Only AppLovin ads

### ISSUE THREAD

**Issue by nooralibutt** [ioridev/flutter_applovin_max#14]
I need to integrate only AppLovin ads and turns out it automatically adds all the pods of mediation adapter.

**Comment by kitet** [comment]
this open issue would just solve a whole lot of junk. kindly allow the commit or implement a way in which users can opt out of the whole library of networks

**Comment by YoussefDahmaneJdid** [comment]
You just need to delete implementation from your build gradle

**Comment by ioridev** [comment]
I do it
