### ISSUE TITLE
Banner Ad IOS

### ISSUE THREAD

**Issue by adriancsbna** [ioridev/flutter_applovin_max#24]
Hi.
Would it be possible to add BannerAds support for IOS? I've seen that they are only available on Android and I would like to use it on IOS.

**Comment by ioridev** [comment]
There are reports that it doesn't work on IOS and I want to fix it but I'm too busy and don't have enough time. Sorry about that.

If you are able to find the cause or solve the problem, it would be great if you could contribute.

**Comment by ioridev** [comment]
Do you know why?
＠superkeka　#11

**Comment by fujiser** [comment]
@ioridev 

It looks like only the Android banner is implemented.
https://github.com/superkeka/flutter_applovin_max/blob/f3a1b59838f4e48a7524b53a1a07d7473d8cf142/lib/banner.dart#L50

**Comment by ioridev** [comment]
ty

> @ioridev
> 
> It looks like only the Android banner is implemented. https://github.com/superkeka/flutter_applovin_max/blob/f3a1b59838f4e48a7524b53a1a07d7473d8cf142/lib/banner.dart#L50
