### ISSUE TITLE
Banner not showing on ios + Note

### ISSUE THREAD

**Issue by medalawi** [ioridev/flutter_applovin_max#35]
Could someone Please help
why the banner ads showing on android but not on  IOS 
How to solve this issue ?
also I found an error on the document that you provide it on pub.dev 
the info.plist code need to be fix 
first line need to close with     >  
`<key>AppLovinSdkKey</key`
Thank you

**Comment by umerzia-7001** [comment]
same issue here

**Comment by ioridev** [comment]
Currently, banner ads are only available for Android.
https://github.com/ioridev/flutter_applovin_max/issues/24

Please wait for the official plugin or implement it.
https://github.com/AppLovin/AppLovin-MAX-Flutter/issues/2
