### ISSUE TITLE
Failed install on iOs

### ISSUE THREAD

**Issue by adriancsbna** [ioridev/flutter_applovin_max#4]
Hello everyone.

I am trying to install this Plugin on iOs 14, but it gives an error and does not download correctly from Cocoapods.

The error occurs when you try to install smaato-ios-sdk.
Does anyone know what can cause the error?

I copy below the error that appears.
I use Flutter 1.22.6

 -> Installing smaato-ios-sdk (21.6.10)
      > Copying smaato-ios-sdk from `/Users/adrian/Library/Caches/CocoaPods/Pods/Release/smaato-ios-sdk/21.6.10-37ec4` to `Pods/smaato-ios-sdk`
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationAdColonyAdapter/AppLovinMediationAdColonyAdapter-4.5.0.0.1/AppLovinMediationAdColonyAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationByteDanceAdapter/AppLovinMediationByteDanceAdapter-3.4.2.3.0/AppLovinMediationByteDanceAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationChartboostAdapter/AppLovinMediationChartboostAdapter-8.4.0.1/AppLovinMediationChartboostAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationFacebookAdapter/AppLovinMediationFacebookAdapter-6.2.0.1/AppLovinMediationFacebookAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationFyberAdapter/AppLovinMediationFyberAdapter-7.8.0.2/AppLovinMediationFyberAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationGoogleAdManagerAdapter/AppLovinMediationGoogleAdManagerAdapter-7.69.0.2/AppLovinMediationGoogleAdManagerAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationGoogleAdapter/AppLovinMediationGoogleAdapter-7.69.0.2/AppLovinMediationGoogleAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationInMobiAdapter/AppLovinMediationInMobiAdapter-9.1.5.0/AppLovinMediationInMobiAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationIronSourceAdapter/AppLovinMediationIronSourceAdapter-7.1.0.0.0/AppLovinMediationIronSourceAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationMaioAdapter/AppLovinMediationMaioAdapter-1.5.6.0/AppLovinMediationMaioAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationMyTargetAdapter/AppLovinMediationMyTargetAdapter-5.9.11.0/AppLovinMediationMyTargetAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationSmaatoAdapter/AppLovinMediationSmaatoAdapter-21.6.10.1/AppLovinMediationSmaatoAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationTapjoyAdapter/AppLovinMediationTapjoyAdapter-12.7.1.1/AppLovinMediationTapjoyAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationTencentGDTAdapter/AppLovinMediationTencentGDTAdapter-4.12.3.1/AppLovinMediationTencentGDTAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationUnityAdsAdapter/AppLovinMediationUnityAdsAdapter-3.6.0.0/AppLovinMediationUnityAdsAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationVungleAdapter/AppLovinMediationVungleAdapter-6.8.1.3/AppLovinMediationVungleAdapter.framework, /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinMediationYandexAdapter/AppLovinMediationYandexAdapter-2.20.0.0/AppLovinMediationYandexAdapter.framework, and /Users/adrian/Documents/GitHub/Globdob/globdob/ios/Pods/AppLovinSDK/applovin-ios-sdk-6.15.2/AppLovinSDK.framework)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:595:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install

**Comment by ioridev** [comment]
Does the build of example work?

**Comment by adriancsbna** [comment]
Hello ioridev, thanks for answering.

Just today I had to send my Mac in for repair. In theory next week I will have it again and do that test.

Best regards.
Adrián Casabuena

**Comment by AlbaMiquel92** [comment]
Hi ioridev.

Sorry for taking so long.
I have tried to download the example app and I was able to launch it on an iPad perfectly.
So it has to be my fault. I'm going to check what I can have different in my App.

Thanks.
All the best.

**Comment by adriancsbna** [comment]
Hi ioridev.

Sorry for taking so long.
I have tried to download the example app and I was able to launch it on an iPad perfectly.
So it has to be my fault. I'm going to check what I can have different in my App.

Thanks.
All the best.

**Comment by adriancsbna** [comment]
Hello ioridev. 

I noticed that I have the same error, but the error gives me in another place, in web_view:

```
 -> Installing webview_flutter (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationAdColonyAdapter/AppLovinMediationAdColonyAdapter-4.5.0.0.3/AppLovinMediationAdColonyAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationByteDanceAdapter/AppLovinMediationByteDanceAdapter-3.4.2.3.0/AppLovinMediationByteDanceAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationChartboostAdapter/AppLovinMediationChartboostAdapter-8.4.0.1/AppLovinMediationChartboostAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationFacebookAdapter/AppLovinMediationFacebookAdapter-6.3.0.0/AppLovinMediationFacebookAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationFyberAdapter/AppLovinMediationFyberAdapter-7.8.2.1/AppLovinMediationFyberAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationGoogleAdManagerAdapter/AppLovinMediationGoogleAdManagerAdapter-8.2.0.1/AppLovinMediationGoogleAdManagerAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationGoogleAdapter/AppLovinMediationGoogleAdapter-8.2.0.1/AppLovinMediationGoogleAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationInMobiAdapter/AppLovinMediationInMobiAdapter-9.1.5.0/AppLovinMediationInMobiAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationIronSourceAdapter/AppLovinMediationIronSourceAdapter-7.1.3.0.0/AppLovinMediationIronSourceAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationMaioAdapter/AppLovinMediationMaioAdapter-1.5.6.1/AppLovinMediationMaioAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationMyTargetAdapter/AppLovinMediationMyTargetAdapter-5.10.1.0/AppLovinMediationMyTargetAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationSmaatoAdapter/AppLovinMediationSmaatoAdapter-21.6.10.2/AppLovinMediationSmaatoAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationTapjoyAdapter/AppLovinMediationTapjoyAdapter-12.8.0.0/AppLovinMediationTapjoyAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationTencentGDTAdapter/AppLovinMediationTencentGDTAdapter-4.12.4.1/AppLovinMediationTencentGDTAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationUnityAdsAdapter/AppLovinMediationUnityAdsAdapter-3.6.0.0/AppLovinMediationUnityAdsAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationVungleAdapter/AppLovinMediationVungleAdapter-6.8.1.5/AppLovinMediationVungleAdapter.framework, /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinMediationYandexAdapter/AppLovinMediationYandexAdapter-2.20.0.0/AppLovinMediationYandexAdapter.framework, and /Users/adrian/Documents/GitHub/person_ai/person_ai/ios/Pods/AppLovinSDK/applovin-ios-sdk-10.0.1/AppLovinSDK.framework)

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:84:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:74:in `each_key'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:74:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:73:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/target_validator.rb:38:in `validate!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:595:in `validate_targets'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Exception: Error running pod install
```
I think it must be a conflict with some plugin you may be using.
If I remove the flutter_applovin_max plugin it works perfectly.


I have tried to add the same plugins to the example and it gives problem with Firebase Plugins.
For example here with the Firebase Analytics Plugin:
```
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 7.1.1, which depends on
      Firebase/Analytics (= 7.3.0) was resolved to 7.3.0, which depends on
        Firebase/Core (= 7.3.0) was resolved to 7.3.0, which depends on
          FirebaseAnalytics (= 7.3.0) was resolved to 7.3.0, which depends on
            GoogleAppMeasurement (= 7.3.0)

    flutter_applovin_max (from `.symlinks/plugins/flutter_applovin_max/ios`) was resolved to 0.1.0, which depends on
      AppLovinMediationGoogleAdapter was resolved to 8.2.0.1, which depends on
        Google-Mobile-Ads-SDK (= 8.2.0.1) was resolved to 8.2.0.1, which depends on
          GoogleAppMeasurement (~> 7.0)
```

Firestore:

```
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 1.0.1, which depends on
          Firebase/Firestore (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseFirestore (~> 7.3.0) was resolved to 7.3.0, which depends on
              nanopb (~> 2.30906.0)

        flutter_applovin_max (from `.symlinks/plugins/flutter_applovin_max/ios`) was resolved to 0.1.0, which depends on
          AppLovinMediationGoogleAdapter was resolved to 8.2.0.1, which depends on
            Google-Mobile-Ads-SDK (= 8.2.0.1) was resolved to 8.2.0.1, which depends on
              GoogleAppMeasurement (~> 7.0) was resolved to 7.8.1, which depends on
                nanopb (~> 2.30907.0)

```
These are the Firebase Plugins that I use in my App:

```
firebase_core: ^1.0.0
firebase_remote_config: ^0.9.0-dev.0
firebase_auth: ^1.0.0
firebase_crashlytics: ^1.0.0
cloud_firestore: ^1.0.0
cloud_functions: ^1.0.0
firebase_analytics: ^7.1.1
```

The Plugins versions are new, they were released at the same time as Flutter 2.0.

Can you think of a way to solve it?

Thanks
Best regards

**Comment by ValentinAhrend** [comment]
Same problem here

**Comment by ValentinAhrend** [comment]
@adriancsbna 
I solved this issue by adding the following lines to my PodFile:

`pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end`

My problem was, that the 'pod install' command, threw the 'The 'Pods-Runner' target has transitive dependencies that include statically...' problem...
