### ISSUE TITLE
Native ads not show

### ISSUE THREAD

**Issue by Reketaka** [ioridev/flutter_applovin_max#40]
java.lang.ClassCastException: com.applovin.impl.mediation.a.d cannot be cast to com.applovin.impl.mediation.a.b

can you help me?

**Comment by Vollinator** [comment]
Please provide more details & your code.

**Comment by Reketaka** [comment]
> Please provide more details & your code.

How you use native ad? 
I see file BannerMax.java he use `new MaxAdView`

and for use native ad web should call `new MaxNativeAdLoader`

https://dash.applovin.com/documentation/mediation/android/getting-started/native-templates

and because native ad not work

**Comment by Vollinator** [comment]
> > Please provide more details & your code.
> 
> How you use native ad? I see file BannerMax.java he use `new MaxAdView`
> 
> and for use native ad web should call `new MaxNativeAdLoader`
> 
> https://dash.applovin.com/documentation/mediation/android/getting-started/native-templates
> 
> and because native ad not work

I think native ads are not implemented in this package. Applovin will release their own SDK for Flutter soon, maybe it is working then.

**Comment by Reketaka** [comment]
> 

i will wait official SDK for Flutter, thank you!

**Comment by thomasmso** [comment]
Hey there - AppLovin just released an official plugin. Please feel free to check it out here: ([docs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration), [repo](https://github.com/AppLovin/AppLovin-MAX-Flutter)).

However, we don't have support for native ads atm. Hopefully [MRECs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/mrecs) will suffice.

**Comment by Reketaka** [comment]
> Hey there - AppLovin just released an official plugin. Please feel free to check it out here: ([docs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/integration), [repo](https://github.com/AppLovin/AppLovin-MAX-Flutter)).
> 
> However, we don't have support for native ads atm. Hopefully [MRECs](https://dash.applovin.com/documentation/mediation/flutter/getting-started/mrecs) will suffice.

tomas can you help? i write to support applovin about block my payment information, but i wait more long time answer can you check or speed up my request? my applovin account alexandr@smutkin.ru 

Thank you so much

**Comment by thomasmso** [comment]
@Reketaka - Please email payments@applovin.com for that, we can only help with technical issue on here

**Comment by Reketaka** [comment]
@thomasmso i send email but don't have answer, ok i understand, thanks for the support
