### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by OttomanDeveloper** [ioridev/flutter_applovin_max#6]
Is there any plan to migrate sound null safety??

**Comment by DDDrop** [comment]
@OttomanDeveloper 
I created a PR for null safety.
If you can't wait for review.
You can import mine. [LINK](https://github.com/DDDrop/flutter_applovin_max)

#7

**Comment by ioridev** [comment]
@DDDrop 
Thank you.
I will review

**Comment by ioridev** [comment]
@DDDrop 
It's closed. Is there a problem?

**Comment by DDDrop** [comment]
@ioridev
By some personal reason, closed it. Sorry about that.
And I PR it again, plz check it.

**Comment by ioridev** [comment]
@DDDrop 
ty!
